### ISSUE TITLE
Translations not loaded with webpack and i18next 2.4.0

### ISSUE THREAD

**Issue by Jenselme** [i18next/i18next-xhr-backend#105]
I am using this backend for i18next with webpack. I followed the instructions provided [here](https://github.com/i18next/i18next-xhr-backend#usage-with-webpack) to make the plugin work. It works fine with i18next 2.3.5 but if I update to 2.4.0, the `loadLocales` function is not executed.

Any idea what the problem is?

**Comment by jamuhl** [comment]
hm...the only change that was made is calling changeLanguage on a timeout: https://github.com/i18next/i18next/commit/ed62c425638c5c762c4f79a8faf1a2ab99656e93#diff-c573044ba770c7e0efcf82de26be326aR106

but this should only result in the init callback being called some ms later....

tests are still green, so i really wondering what happened...will check this later...but can you paste your configuratiion...not sure but might be something wrong.

**Comment by jamuhl** [comment]
tested on react-i18next all seems to run as expected...please post your config and on how you test that stuff gets not loaded...

**Comment by Jenselme** [comment]
Here is my config:
```js
{
    backend: {
        loadPath: '{{lng}}',
        parse: (data) => data,
        ajax: loadLocales,
    },
    lng: language,
    attributes: ['t', 'i18n'],
    fallbackLng: ['en', 'fr'],
    debug: false,
}
```

and `loadLocales`:
```js
function loadLocales(url, options, callback, data) {
    switch (url) {
        case 'en':
            callback(enTranslations, { status: '200' });
            break;
        case 'fr':
             callback(frTranslations, { status: '200' });
             break;
        default:
            callback(null, { status: '404' });
            break;
    }
}
```

To check that nothing is loaded: I witness that nothing is translated. I put a `console.log` in `loadLocales` and didn't see the corresponding line in my console.

For your concern, I am using i18next with [aurelia-i18n](https://github.com/aurelia/i18n). But as said earlier, I only have to update i18next to 2.4.0 to have the bug and downgrade to 2.3.5 to remove it, so I suppose this comes from here.

**Comment by jamuhl** [comment]
tried again with adding your loadLocales and parse to the react sample...still that works i get a log output in loadLocales...

what is `language`set to on init? can you set debug to true and post console output?

**Comment by Jenselme** [comment]
`language` is set to `let language = navigator.language.split('-')[0];`.

With the react example at https://github.com/i18next/react-i18next/tree/master/example, I have the following error (I suspect there's something wrong in the webpack config):
```
ERROR in ./app/main.js
Module not found: Error: Cannot resolve module 'react-i18next' in /tmp/react-i18next/example/app
 @ ./app/main.js 15:20-44

ERROR in ./app/components/View.js
Module not found: Error: Cannot resolve module 'react-i18next' in /tmp/react-i18next/example/app/components
 @ ./app/components/View.js 15:20-44

ERROR in ./app/components/AnotherComponent.js
Module not found: Error: Cannot resolve module 'react-i18next' in /tmp/react-i18next/example/app/components
 @ ./app/components/AnotherComponent.js 11:20-44
```

I tried full relative path like `../node_modules/react-i18next` without success.

**Comment by jamuhl** [comment]
you will need to run `npm build` on project first....

**Comment by Jenselme** [comment]
> you will need to run npm build on project first (not example)....

Thanks for the precision, that worked. The react example seem to work fine.

Here is my console output with debug at true and version 2.3.5:

```
i18next::backendConnector: loaded namespace translation for language en Object { OPEN: "Open", TAKEN: "Taken", cards: Object, game: Object, global: Object, site: Object, trumps: Object } logger.js:24:35
i18next::backendConnector: loaded namespace translation for language fr Object { OPEN: "Ouvert", TAKEN: "Pris", cards: Object, game: Object, global: Object, site: Object, trumps: Object } logger.js:24:35
i18next: languageChanged en logger.js:24:35
i18next: initialized Object { debug: true, ns: Array[1], defaultNS: Array[1], fallbackLng: Array[2], fallbackNS: false, whitelist: false, load: "all", preload: false, keySeparator: ".", nsSeparator: ":", 18 more… } logger.js:24:35
```

Here is with version 2.4.0:
```
i18next::translator: missingKey undefined translation game.create.popup_select_avatar game.create.popup_select_avatar logger.js:24:35
i18next::translator: missingKey undefined translation global.save global.save logger.js:24:35
i18next: languageChanged en logger.js:24:35
i18next: initialized Object { debug: true, ns: Array[1], defaultNS: Array[1], fallbackLng: Array[2], fallbackNS: false, whitelist: false, load: "all", preload: false, keySeparator: ".", nsSeparator: ":", 18 more… }
```

Changing the language does nothing.

**Comment by jamuhl** [comment]
do you wait on i18next initialized callback before translating the UI?

`i18next.init(options, function(err, t) {  /* loaded - start translating UI */   });`

**Comment by Jenselme** [comment]
I managed to find that the problem comes from the timeout defined [here](https://github.com/i18next/i18next/blob/master/src/i18next.js#L106) in version 2.4.0. If I remove it, it works fine.

So I guess that something somewhere in aurelia-i18n is not waiting correctly on the promise. I'll try to find out what tomorrow.

Thanks for you help!

**Comment by jamuhl** [comment]
Yes...the timeout is new...and enables doing something between init and load (eg. like adding resourceBundles before loading - resulting in that bundle needs not be loaded. That's an important feature for universal rendering).

Will be open to suggestions making it work again...but hopefully this could be handled in aurelia-i18n.
