### ISSUE TITLE
Clientside usage help?

### ISSUE THREAD

**Issue by Laro88** [i18next/i18next-xhr-backend#121]
Getting i18next to function clientside is apparently more difficult than on the server.
Any chance there is a "guideline" available.

What I have is Node.JS + Express and Jade. I do however also need some translations in clientside script, so I include the clientside scripts i18next.min.js, i18nextXHRBackend.min.js and the jquery-i18next.js files.
The configuration is confusing me - what is needed clientside to make the $.t or i18n.t operational?

**Comment by jamuhl** [comment]
https://github.com/i18next/jquery-i18next/blob/master/example/sample.html

just add the xhr backend to the mix...

if you use the https://github.com/i18next/i18next-express-middleware#add-routes multiload route on server side assert you change xhr to loadPath to `/locales/resources.json?lng={{lng}&ns={{ns}}` and enable allowMultiLoading: https://github.com/i18next/i18next-xhr-backend#backend-options

else serve the assets from your server as static assets

**Comment by jamuhl** [comment]
closing for now...feel free to reopen
