### ISSUE TITLE
Unable to --save in bower

### ISSUE THREAD

**Issue by San7hos** [i18next/i18next-xhr-backend#151]
bower                     invalid-meta The "main" field cannot contain minified files
bower i18next-xhr-backend#*     cached https://github.com/i18next/i18next-xhr-backend.git#0.5.4
bower i18next-xhr-backend#*   validate 0.5.4 against https://github.com/i18next/i18next-xhr-backend.git#*

**Comment by jamuhl** [comment]
no idea what causes this...the file looks ok to me...

**Comment by San7hos** [comment]
At first the i18next extensions/plugins were not added to the bower.json file. I have now tried to install them one by one and it works. It is probably my issue, sorry.
