### ISSUE TITLE
Allow multi loadPath values

### ISSUE THREAD

**Issue by M3lkior** [i18next/i18next-xhr-backend#155]
Hi,

backend options admit a single string for loadPath option.

It is possible to implement a loadPath option to allow multi path like

```
 backend: {
            loadPath: ['/app/locales/{{lng}}/{{ns}}.json', '/fwk/locales/{{lng}}/{{ns}}.json']
        }
```

**Comment by jamuhl** [comment]
is there some rule to know which route resource should be loaded by? or just try both?

really not sure what the use case is. but we moved the backends to be separated from i18next core right out of this reason...if you look at the source code it's a simple 135 loc. http://i18next.com/docs/ownplugin/#backend documents the API for building your own backend.

**Comment by M3lkior** [comment]
Here is my use case :

- Loading bundles from fwk-modules to be avalaibles in the app (path must be for example /node_modules/fwk/locales/.../fwk.json)
- Loading app's bundles for custom developpement

Because of components of my app can need to use pre-defined labels, defines in my fwk-module

**Comment by jamuhl** [comment]
ok i see...there are two options:

a) you create a custom backend - seems to be the easiest way to provide what you need - as you can adapt it fully to your needs
b) use two instances of i18next using own instances of the i18next-xhr-backends

**Comment by jamuhl** [comment]
closing for now...feel free to reopen if still in need for this.

**Comment by trajano** [comment]
Is there an existing npm module that would do this already?

**Comment by trajano** [comment]
I'm actually stuck on this one as I am trying to figure out what the API for callback is since I can't seem to see it documented in http://i18next.com/docs/ownplugin/

**Comment by trajano** [comment]
My guess is:
`callback(error, retry)` or `callback(null, data)`

**Comment by jamuhl** [comment]
read: `function(err, res)``

res is of type javascript object:

```
{
  key1: 'value1',
  key2: 'value2'
}
```

readMulti: `function(err, res)``

res is of type javascript object:

```
{
  en: {
    translation: {
      key1: 'value1',
      key2: 'value2'
    }
  },
  de: {
    translation: {
      key1: 'value1',
      key2: 'value2'
    }
  }
}
```

**Comment by jamuhl** [comment]
or in error case callback(err, retry) like you said

**Comment by caasi** [comment]
It is possible to create a backend module to merge multiple backends. The module is almost identical to [i18next-chaind-backend](https://github.com/i18next/i18next-chained-backend), so I just show the `read` function:

```typescript
class Backend extends BackendModule<MergedBackendOptions> {
  read(language: string, namespace: string, callback: ReadCallback) {
    const run = this.backends.reduceRight((next, backend) => (err, data) => {
      if (err) return next(err, undefined) as never;
      backend.read(language, namespace, (err, newData) => {
        if (err) return next(null, data); // skip this backend
        return next(null, merge(data, newData));
      });
    }, callback);
    run(null, {});
  }
}
```

**Comment by adrai** [comment]
> It is possible to create a backend module to merge multiple backends. The module is almost identical to [i18next-chaind-backend](https://github.com/i18next/i18next-chained-backend), so I just show the `read` function:
> 
> 
> 
> ```typescript
> 
> class Backend extends BackendModule<MergedBackendOptions> {
> 
>   read(language: string, namespace: string, callback: ReadCallback) {
> 
>     const run = this.backends.reduceRight((next, backend) => (err, data) => {
> 
>       if (err) return next(err, undefined) as never;
> 
>       backend.read(language, namespace, (err, newData) => {
> 
>         if (err) return next(null, data); // skip this backend
> 
>         return next(null, merge(data, newData));
> 
>       });
> 
>     }, callback);
> 
>     run(null, {});
> 
>   }
> 
> }
> 
> ```

with i18next-chained-backend you can do [fallback](https://www.i18next.com/how-to/backend-fallback) or [caching](https://www.i18next.com/how-to/caching)
if you need a more custom behaviour you may need to create your own backend: https://www.i18next.com/misc/creating-own-plugins
