### ISSUE TITLE
Pass url as the second parameter for parsing data

### ISSUE THREAD

**Issue by cheton** [i18next/i18next-xhr-backend#187]
Hi @jamuhl,

I had a use case that will need to modify translation keys only for specific resource files. May I know if it's possible to add `url` as the second parameter to the `parse` option? For example:

```js
{
  // parse data after it has been fetched
  parse: function(data, url) {
    // do something for specific url
    return data;
  }
}
```

**Comment by jamuhl** [comment]
just published i18next-xhr-backend@0.6.0 which will add this.
