### ISSUE TITLE
Feature request: Add json5 support

### ISSUE THREAD

**Issue by arve0** [i18next/i18next-xhr-backend#2]
Suggestion, add [json5](https://github.com/aseemk/json5) support, like in [i18next-node-fs-backend](https://github.com/i18next/i18next-node-fs-backend).

This might already be possible already?

**Comment by jamuhl** [comment]
Won't happen considering json5 used by a minority - would add extra kb for the ones not using it.

But it's very easy to create additional backends - why not create one and share with community?

**Comment by arve0** [comment]
Ok. Will you accept a PR with the option `parse`, a function that parses the fetched json?

**Comment by jamuhl** [comment]
that would be a good alternative...go for it....will be merged
