### ISSUE TITLE
Bundle not loaded when i18n is initialized with options.resources

### ISSUE THREAD

**Issue by at0g** [i18next/i18next-xhr-backend#201]
Hello,

I'm experiencing an issue with loading a resource bundle on-demand, but only when passing `options.resources` to `i18next.init`. 

Pretty sure my config is all ok, as if I comment out `options.resources`, then everything gets loaded on-demand and works as expected. This is not an acceptable work around for my use case (I am using universal rendering, where `options.resources` are pre-populated from the server)

**Comment by jamuhl** [comment]
if you pass in options.resources then i18next won't load any resources - it expects you fill all manually.

use `i18next.addResourceBundle` to fill pre-populated values from server: http://i18next.com/docs/api/#add-resource-bundle

**Comment by at0g** [comment]
ok thanks - that was really fast, I was just about to post a link to a reproduction:
https://github.com/at0g/i18next-xhr-backend-issue-201

I'll try `i18next.addResourceBundle` and hopefully close this issue 👍
