### ISSUE TITLE
Question: Using TypeScript with i18next-xhr-backend

### ISSUE THREAD

**Issue by kevmeister68** [i18next/i18next-xhr-backend#234]
Firstly, I do not profess to be uber-knowledgeable concerning modules loaders and the like.

The problem I have is that if I take your typings file for TypeScript, which refers to the module name as "i18next-xhr-backend", then I can get my typescript code to build, because this kind of code works:

import * as Backend from 'i18next-xhr-backend'

The problem is that my code will not run, because it seems that your UMD build of i18next-xhr-backend (I'm looking at the jspm module code-base), uses this define:

    (function (global, factory) {
      typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
      typeof define === 'function' && define.amd ? define('i18nextXHRBackend', factory) :
      (global.i18nextXHRBackend = factory());
    }(this, function () { 'use strict';

In other words the module is named i18nextXHRBackend.

I am using RequireJS 2.1.20 as my module loader so I basically have to change "something" to a build to function - in my case I have changed the typings .d.ts file to change its module name to i18nextXHRBackend.

(A side effect is that I also have to change the way I register the typings file, using:
typings install --global i18nextXHRBackend=file:/some/path/to/my/i18next-xhr-backend.d.ts

What is interesting about this is when I install i18next-xhr-backend via jspm, the config.js is updated to define the module name as "i18next-xhr-backend". I don't know if that is correct or not since I don't use the SystemJS loader, but it is disconcerting that I need a different module name in RequireJS compared to the "automatically supplied one" injected into config.js.

I am loathe to call this a bug, but I would certainly like to understand what is going on.

**Comment by jamuhl** [comment]
checkout v1.0.1 which changed export to be not named.
