### ISSUE TITLE
dynamic loadPath

### ISSUE THREAD

**Issue by danielwagner** [i18next/i18next-xhr-backend#235]
I need to be able to fetch translation files from URLs determined by looking up a configuration map whenever resources are requested. This could be achieved by allowing the _loadPath_ config setting to optionally accept a function. Would you be willing to consider a pull request if I opened one?

**Comment by jamuhl** [comment]
Sure. But wont be able to publish before next monday as i am on holiday

**Comment by danielwagner** [comment]
Great! Enjoy your holiday.
