### ISSUE TITLE
Expected payload for single vs multi?

### ISSUE THREAD

**Issue by rosskevin** [i18next/i18next-xhr-backend#237]
I have implemented a custom ruby backend and have single namespace requests working, for example:

``` javascript
// GET /locales/resources.json?lng=en&ns=common
{foo: "bar"}
```

But this has no room for multiple languages or namespaces.

Now that I'm implementing multiple languages _and_ multiple namespaces via `allowMultiLoading`, how should the payload be structured?

``` javascript
// GET /locales/resources.json?lng=es+en&ns=common+other
???
```

**Comment by rosskevin** [comment]
After debugging, here is the conclusion that I can draw:

1.  **Without** `allowMultiLoading: true`, i18next libraries don't like to see preceeding `"en": { "common": {}}` (preceding `lng` and `ns`)
2.  **With** `allowMultiLoading: true`, i18next libraries **want** to see the preceding  `lng` and `ns`.

So, a multiloading payload structure appears to be:

```javascript
{
    "en": {
        "common": {
            "foo": "bar"
        }
    },
    "es": {
        "common": {
            "foo": "pub"
        }
    }
}
```

Please correct any misunderstandings I may have.  If this is correct, it might be useful to document somewhere.

**Comment by jamuhl** [comment]
@rosskevin correct...will add this info to the doc asap.

**Comment by jamuhl** [comment]
updated docs: https://www.i18next.com/misc/creating-own-plugins.html#backend
