### ISSUE TITLE
Can't get it to POST missing translations

### ISSUE THREAD

**Issue by rchanou** [i18next/i18next-xhr-backend#241]
I can request and load translations from my server just fine. However, I made some calls for missing translation keys, and I don't even see POST requests in the console for any sort of translations endpoint. Assuming this isn't a bug, how would I get the backend to try to add missing translations?

**Comment by jamuhl** [comment]
did you set `saveMissing=true` on init i18next? else there won't be a call to post missing...

**Comment by rchanou** [comment]
Yes, that was, it, thanks :)

**Comment by jamuhl** [comment]
you're welcome.

a little advertising: did you already had a look at http://locize.com our localization as a service platform?

**Comment by rchanou** [comment]
Looks interesting, thanks!
