### ISSUE TITLE
addPath: doesn't POST for missing

### ISSUE THREAD

**Issue by p5ych0** [i18next/i18next-xhr-backend#242]
please correct me if I misunderstood the addPath option.
was it intended to POST missing locale, namespace, option?
to me that would make a lot of sense

**Comment by jamuhl** [comment]
it posts the missing keys - but only if i18next option saveMissing is set to true on init

**Comment by p5ych0** [comment]
I can see it gets one language, then a fallback language, but can't see any post request.
both saveMissing=true and saveMissingTo=all props exist in init section

**Comment by jamuhl** [comment]
is it possible that your locale is `en-US` and you just have `en` in your whitelist?
with fallback `en` it would result in current = null and use just fallback `en`?

you can set `nonExplicitWhitelist: true` on init if you want allow en-US for whitelisted en.

else you might debug https://github.com/i18next/i18next/blob/master/src/Translator.js#L121 and check what ends in lngs.

there are a few tests checking this should work as expected: https://github.com/i18next/i18next/blob/master/test/backward/v1.11.1.compat.js#L1164 so i think it should work

**Comment by jamuhl** [comment]
closing...feel free to reopen if still valid issue.
