### ISSUE TITLE
ES distribution build is the same as the CommonJS build

### ISSUE THREAD

**Issue by MrSlide** [i18next/i18next-xhr-backend#245]
Unlike other i18next plugins which have ES6 modules in the ES distribution directory, this one has the same files as the CommonJS build. This is preventing the module from being bundled with Rollup.

**Comment by jamuhl** [comment]
can you try: i18next-xhr-backend@1.2.1

seems an upgrade of babel-preset-es2015-native-modules did kill it - downgraded and seems ok now.

**Comment by MrSlide** [comment]
That fixed it, thanks ;)
