### ISSUE TITLE
allowMultiLoading is sending wrong GET

### ISSUE THREAD

**Issue by mrpatiwi** [i18next/i18next-xhr-backend#251]
Expected: `/locales/resources.json?lng=es-ES+es+en&ns=translation`
But it's sending: `/locales/es-ES+es+en/translation.json`

With `allowMultiLoading: true`.

**Comment by jamuhl** [comment]
you will also need to change `loadPath: '/locales/resources.json?lng={{lng}}&ns={{ns}}',` for multiload to work

**Comment by mrpatiwi** [comment]
That fixed my problem, thanks!
I think the documentation is not clear enough about `allowMultiLoading` usage

**Comment by jamuhl** [comment]
Suggestion to improve or PR would be welcome...

**Comment by jamuhl** [comment]
added some hint in readme
