### ISSUE TITLE
Use fetch api when supported

### ISSUE THREAD

**Issue by perrin4869** [i18next/i18next-xhr-backend#252]
I'm using `i18next` in a service worker setup right now with this `xhr` backend, however, there was one obstacle to get it working: `XMLHttpRequest` is not defined in the service worker context. I did manage to get the backend working in the following manner however:

```js
import i18next from 'i18next';
import i18nextXHR from 'i18next-xhr-backend'; // eslint-disable-line import/no-unresolved,import/no-extraneous-dependencies

let t = null;

self.addEventListener('activate', (event) => {
  event.waitUntil(new Promise((resolve, reject) => {
    i18next
      .use(i18nextXHR)
      .init({
        fallbackLng: ['ja', 'en', 'zh'],
        preload: ['ja', 'en', 'zh'],
        ns: 'translation',
        defaultNS: 'translation',
        keySeparator: false, // Allow usage of dots in keys
        nsSeparator: false,
        backend: {
          loadPath: '/locales/{{lng}}/{{ns}}.json',
          ajax(url, options, cb) {
            fetch(url, options)
              .then((res) => {
                if (res.ok) {
                  return res.text()
                    .then((json) => {
                      cb(json, res);
                    });
                }

                return new Error('Error loading translation json');
              });
          },
        },
      }, (err, _t) => {
        if (err) {
          reject(err);
          return;
        }

        t = _t;
        resolve();
      });
  }));
});
```

By using the `ajax` option and using the `fetch` API, this backend works like charm... however, maybe it's a good idea to use the `fetch` API here wherever it's supported by default? It's a more modern API supported by modern browsers, and would make using `i18next` in service worker contexts, or other modern context much more easy

**Comment by jamuhl** [comment]
currently there is no plan for that....as we do not just want to support modern browsers.

but i'm open to add a new backend `i18next-fetch-backend` to the list on i18next.com if you like to support that (simple to do)

**Comment by perrin4869** [comment]
Well, what I meant was adding an API check to this backend, but yeah a `fetch` backend would do just fine too, I'll do that this week then. It will be mostly a copy and paste of this backend though

**Comment by perrin4869** [comment]
Actually, what do you think of this as the `fetch-backend`:

```js
import XHRBackend from 'i18next-xhr-backend';

class FetchBackend extends XHRBackend {
  constructor(services, options = {}) {
    options.ajax = options.ajax || ((url, options, cb) => {
      fetch(url, options)
        .then((res) => {
          if (res.ok) {
            return res.text()
              .then((json) => {
                cb(json, res);
              });
          }

          return new Error('Error loading translation json');
        });
    });

    super(services, options);
  }
}
```

Just tested it and seems to work in my case. I'll publish it as an npm module tomorrow

**Comment by perrin4869** [comment]
Just published the module [here](https://www.npmjs.com/package/i18next-fetch-backend)

**Comment by jamuhl** [comment]
will add it to i18next.com asap

**Comment by jamuhl** [comment]
added http://i18next.com/docs/ecosystem/#backends

**Comment by jamuhl** [comment]
thanks for sharing
