### ISSUE TITLE
Pass values for `data` and `cache` through options

### ISSUE THREAD

**Issue by nikolay-borzov** [i18next/i18next-xhr-backend#254]
In [ajax.js](https://github.com/i18next/i18next-xhr-backend/blob/master/src/ajax.js) declared `ajax` function:

`function ajax(url, options, callback, data, cache) {`

I don't see a way to pass `data` and `cache` parameters from outside. It would be handy for adding build version:

```
backend: {
  // add build version to reset browser cache
  loadPath: '{{ns}}/translation_{{lng}}.json'
  data: { v: buildVersion }
}
```
Could be implemented like this:
```
function ajax(url, options, callback, data, cache) {
  data = data || options.data;
  cache = cache || options.cache;

  // Must encode data
  if(data && typeof data === 'object') {
  ...
```

Currently I add parameters likes this: 
```
backend: {
  // add build version to reset browser cache
  loadPath: '{{ns}}/translation_{{lng}}.json?v=' + buildVersion,
}
```

**Comment by jamuhl** [comment]
data is only used on post request: https://github.com/i18next/i18next-xhr-backend/blob/master/src/index.js#L74

cache flag is only used if data is passed too

as stated it's just some gist code i copied...so it's more some internal code. The calls to ajax function are limited too - as the got called by read and change - not much one could override there.

you can override the ajax call directly: https://github.com/i18next/i18next-xhr-backend/blob/master/src/index.js#L11

or if you like...provide a PR with the change mentioned about - will merge and publish that asap

**Comment by nikolay-borzov** [comment]
Have a few question about coding:
Can I use es6 features like Object.keys, Array.reduce, strint interpolation and etc?

**Comment by jamuhl** [comment]
When submitting data from backend to client? it's json not javascript!?!?

**Comment by nikolay-borzov** [comment]
I'm talking about my changes. I'm wtiring a helper function:

```
function addQueryString(url, params) {
  if (params && typeof params === 'object') {
    let queryString = '',
      e = encodeURIComponent;

    for (var paramName in params) {
      queryString += `&{e(paramName)}={e(params[paramName])}`;
    }

    if(!queryString) {
      return url;
    }

    url = url + (url.includes('?') ? '&' : '?') + queryString.slice(1);
  }

  return url
}
```

Should I only use es5 feature to support old browsers?

**Comment by jamuhl** [comment]
if you run that snipplet to babel like your other code you can use es6 - else not...depends on your setup

**Comment by nikolay-borzov** [comment]
I can't push my branch for some reason. I will try to fight it tomorrow. Otherwise I will just post gist with my changes

**Comment by nikolay-borzov** [comment]
Created a PR: https://github.com/i18next/i18next-xhr-backend/pull/255

**Comment by jamuhl** [comment]
merged
