### ISSUE TITLE
Deep/inner/nested keys do not work if key coincides with a string function.

### ISSUE THREAD

**Issue by rally25rs** [i18next/i18next-xhr-backend#258]
If you have a translation json file that contains:

```
{
  "action": {
    "add": "Add",
    "search": "Search",
    "length": "Length"
  }
}
```

and you try to resolve "add", it works correctly:

```
i18next.t('action.add'); // "Add"
```

However, if you try to resolve "search" it actually returns the `string.search` function:

```
i18next.t('action.search'); // function search() { [native code] }
```

Same with "length":

```
i18next.t('action.length'); // 7
```

You can test that the returned value is actually the `string.search` function:

```
"".search === i18next.t('action.search'); // true
```

-----

This is not the case if you use raw i18next without this xhr backend:

```
i18next.init({
  lng: 'en',
  resources: {
    en: {
      translation: {
        "action": {
          "add": "Add",
          "search": "Search",
          "length": "Length"
        }
      }
    }
  }
});

i18next.t('action.search'); // "Search"
```

**Comment by jamuhl** [comment]
Thanks for further investigation...will have a look at xhr-backend asap

**Comment by rally25rs** [comment]
incase it helps, here is how I initialize i18n. it might help reproduce the issue...

```
    const i18nextOptions = {
      lngs: ['en'],
      fallbackLng: 'en',
      ns: namespaces,
      defaultNS: 'ns1'],
      fallbackNS: ['ns1', 'ns2'],
      resources: undefined,
      interpolation: {
        format: function(value, format, lng) {
          if(value instanceof Date) {
            return moment(value).format(format);
          } else if(value instanceof moment) {
            return value.format(format);
          }
          return value;
        },
        escape: function(value) {
          return value;
        }
      },
      backend: {
        loadPath: 'locales/{{lng}}/{{ns}}.json',
      }
    };

    i18nextInstance = window.i18next.createInstance();
    i18nextInstance.use(window.i18nextXHRBackend);

    i18nextInstance.init(i18nextOptions, () => {
        i18nextInstance.loadLanguages(['en']);
    });
```

**Comment by jamuhl** [comment]
1) i tried to reproduce this here: https://github.com/i18next/i18next-xhr-backend/blob/master/test/backendConnector.load.spec.js#L21

by adding your json and assert the keys where what expected -> could not reproduce it

2) i tried reproducing here: https://github.com/i18next/i18next/blob/master/test/backward/v1.11.1.compat.js#L138

same could not reproduce it

3) finally i tried to reproduce on the react-i18next sample...again without success: https://github.com/i18next/react-i18next/tree/master/example/webpack2

Could you please provide a reproducable sample or test? i'm sure i miss some detail - but don't get on it. really strange

**Comment by rally25rs** [comment]
Well, I did a little more debugging and figured out what is happening...

I have 2 files/namespaces, and it turns out they both defined the same key:

namespace1.json
```
{
  "action": "Actions"
}
```

namespace2.json
```
{
  "action": {
    "search": "Search"
  }
}
```

i18next is configured to check "namespace1" first, so it finds "action" to be the string "Action", then returns the `.search` property of that string.

Oops :( Oh the struggles of maintaining unique keys :)

-----

I'll go ahead and close this issue because it's a bad edge case on my end. Perhaps a future feature of i18next could be to detect this kind of clash (a string on one NS but an object in another) but is clearly something I need to handle.

Sorry to have burned up a bunch of your time looking at this, but I greatly appreciate how quickly you responded.
I always enjoy supporting well-maintained open source projects 👍
