### ISSUE TITLE
yaml loading

### ISSUE THREAD

**Issue by bonesoul** [i18next/i18next-xhr-backend#259]
i'm using https://github.com/i18next/i18next-node-fs-backend for my translations and using yaml format.

i also want to load them on client - does this package even support yamls?

**Comment by jamuhl** [comment]
No...adding a yaml parser would add to much weight to client.

a) override the parse function https://github.com/i18next/i18next-xhr-backend/blob/master/src/index.js#L9 using https://www.npmjs.com/package/yamljs
b) convert those on backend
c) write your own backend using https://www.npmjs.com/package/yamljs converting yaml on the clientside (should be rather easy)
