### ISSUE TITLE
Q: How to fallback to a static resource if backend is unavailable

### ISSUE THREAD

**Issue by Dubes** [i18next/i18next-xhr-backend#262]
**Setup:**  _based on Create React App_
"react-i18next": "^4.8.0",
"i18next": "^8.4.3",
"i18next-xhr-backend": "^1.4.2",

**Problem Statement**
I have a service which enables end users to configure a custom dictionary which is exposed over a rest end point (they don't have to, but are allowed to if they wish).  I would love to fallback to a "bundled" dictionary,  which we provide out of the box as a static resource if no custom dictionaries are found. The loadUrl for both these assets would be different.

Any ideas on how it can be achieved? I am not even sure if this should be a concern for XHR backend or for i18next init method. 

**My ideas so far**
Use a custom XHR function to achieve this. I do not want to reinvent the wheel, but at the same time, that seems to be the reason behind this option to be present.

Just wondering if a better option exists ( I am new to i18next ecosystem and was able to start very fast, but I do not know the inner workings of it yet, any hint would be appreciated)

**Comment by jamuhl** [comment]
Best options i guess would be creating a own backend plugin (based on xhr) -> you do loading xhr for the custom translations from the rest endpoint and merge those with the values you provide (bundled or from a own rest endpoint).

Creating own plugin is rather easy using the exiting xhr-backend + reading https://www.i18next.com/misc/creating-own-plugins.html#backend

If you like to provide a simpler way for your customers to create own translations you might have a look at our https://locize.com

**Comment by Dubes** [comment]
Thank you for the great hint! I will give it a shot. 
Closing the issue.

**Comment by jamuhl** [comment]
Awesome...if you run into troubles - let me know
