### ISSUE TITLE
XML Parsing Error: not well-formed in Firefox

### ISSUE THREAD

**Issue by Eliastik** [i18next/i18next-xhr-backend#263]
I use i18next with i18next-xhr-backend for my Firefox extension, and I encountered an error message in the console  : 

`XML Parsing Error: not well-formed ...`

This is due to the XHR backend. When the MIME type isn't set by the server, Firefox believe that the file requested is in XML format. To fix this issue, I have edited the code with the following changes in the ajax function (line 73, after the if (data) condition) : 

````
if (x.overrideMimeType) {
      x.overrideMimeType("application/json");
}
````

The problem was fixed after that.

**Comment by jamuhl** [comment]
feel free to add a PR so we could merge this in

**Comment by Eliastik** [comment]
Issue fixed.
