### ISSUE TITLE
src/index.js could be called src/i18nextBrowserLanguageDetector.js?

### ISSUE THREAD

**Issue by daKmoR** [i18next/i18next-xhr-backend#269]
or `i18next-browser-languageDetector.js`

if you currently import it - it will look like this
```
import i18next from '../i18next/dist/es/i18next.js';
import i18nextXHRBackend from '../i18next-xhr-backend/dist/es/index.js';
import i18nextBrowserLanguageDetector from '../i18next-browser-languageDetector/dist/es/index.js';
```

something like the following "looks" nicer right?
```
import i18next from '../i18next/dist/es/i18next.js';
import i18nextXHRBackend from '../i18next-xhr-backend/dist/es/i18nextXHRBackend.js';
import i18nextBrowserLanguageDetector from '../i18next-browser-languageDetector/dist/es/i18nextBrowserLanguageDetector.js';
```

just a suggestion as I was importing it like the second one out of habit and as it was not working I had to take a look how the file was actually called. So it's nothing serious :p

just close if you wish to keep as is.
or ping if you want an pull request.

**Comment by jamuhl** [comment]
Open to that change...just make an additional index.js file exporting that also - so we do not break existing projects.
