### ISSUE TITLE
one json file for all languanges

### ISSUE THREAD

**Issue by unutoiul** [i18next/i18next-xhr-backend#270]
Hi,

If i load only one json file for all languages how this suppose to work?

Thanks,
Lucas

**Comment by jamuhl** [comment]
there is `allowMultiLoading` https://github.com/i18next/i18next-xhr-backend#backend-options

request: `/locales/resources.json?lng=de+en&ns=ns1+ns2` and expects a response in form of:

```json
{
    "en": {
        "common": {
            "foo": "bar"
        }
    },
    "es": {
        "common": {
            "foo": "pub"
        }
    }
}
```

**Comment by pors** [comment]
Hi, I have a similar use case: I have all text for a specific language in one file, like:

```
{
        "common": {
            "foo": "bar"
        },
        "someComponent": {
            "foo2": "bar2"
        }
}
```

which is placed in `/locales/es/resources.json` and:

```
        backend: {
            loadPath: '/static/locales/{{lng}}/resources.json?ns={{ns}}',
            allowMultiLoading: true
        }
```

This doesn't work apparently. What is the way to go here?

Also: is it possible to load the English text via `i18next.init({resources:...})`, and the other languages via XHR?

Thanks!

**Comment by jamuhl** [comment]
@pors no not possible  - you can't pass in resources on init and use the backend to load. -> option would be to use https://www.i18next.com/api.html#addresourcebundle to pass initial content...

having all namespaces in one file...sounds like a good fit for creating a own backend: https://www.i18next.com/misc/creating-own-plugins.html#backend

**Comment by pors** [comment]
thanks for the speedy reply
