### ISSUE TITLE
the first lang is dev and after is en

### ISSUE THREAD

**Issue by unutoiul** [i18next/i18next-xhr-backend#271]
backend: {
            // for all available options read the backend's repository readme file
            loadPath: url+'/i18n_{{lng}}', 
}
I can see two requests happening one with dev and one with en...what is the reason and how can i remove the dev request?

i have debug:false

Thanks,
Lucas

**Comment by jamuhl** [comment]
`dev` is default fallbackLng (set that to `en`) -> https://www.i18next.com/configuration-options.html#languages-namespaces-resources

or set fallbackLng to false if you don't like to show fallback values for missing translations (in that case key would be shown)

also have a look at load options: language codes to lookup, given set language is 'en-US': 'all' --> ['en-US', 'en', 'dev'], 'currentOnly' --> 'en-US', 'languageOnly' --> 'en'
