### ISSUE TITLE
Unexpected URL /locales/en/common.json

### ISSUE THREAD

**Issue by NewBee2014** [i18next/i18next-xhr-backend#272]
I tried to use this plugin to configure the **pathLoad** paramater in create-react-native-app project ( [example with react-i18next](https://github.com/i18next/react-i18next/tree/master/example/react-native-expo)) but I am facing with the issue "Unexpected URL /locales/en/common.json". Could you please let me know what I should do for that parameter?

My project structure is
--App.js
--src
----resources
------i18n
--------i18n.js
--------locales
----------en
------------common.json

Thanks.

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-xhr-backend#backend-options

loadPath must be full qualified...something like http://localhost:3000/locales/... during development and https://yourserver.com/locales/... for production

**Comment by NewBee2014** [comment]
Thank you for your answer quickly. 

So in my case, I should set it as "http://localhost:3000/locales/en/common.json", and it will scan my project for that "locales" directory, no matter what this directory is? Or I should move that "locales" directory to specific place?

**Comment by jamuhl** [comment]
no...it's an xhr request....there must be a server serving those files. Like eg. your API server providing your app with data.

Other options are to bundle the translations with your app - or using our localization as a service tier https://locize.com to host those translations

**Comment by NewBee2014** [comment]
Got you, thank you for your explanation.
