### ISSUE TITLE
Make it universal ?

### ISSUE THREAD

**Issue by Vincz** [i18next/i18next-xhr-backend#273]
I'm currently using i18next for an universal react application, so there is a node server to render the first hit and the react client. 
Both are using a remote i18next backend.
The client use this one, and the server is supposed to use https://github.com/i18next/i18next-node-remote-backend (last updated 2 years ago).

Wouldn't it be better to have only one "universal" package able to run on node AND in the browser ?
There is now plenty of universals "xhr / request" packages available like axios, superagent, etc...

What do you think ?

**Comment by jamuhl** [comment]
Why not creating one - and share with the community? something like `i18next-universal-backend` ?!?

the API for backends are rather simple: https://www.i18next.com/misc/creating-own-plugins.html#backend
