### ISSUE TITLE
Underscore in path

### ISSUE THREAD

**Issue by McGiverGim** [i18next/i18next-xhr-backend#275]
Hi! I'm trying to load the translations file in a chrome app, so the translations are located inside `_locales` folder. My init is like this:
```
    i18next
        .use(i18nextXHRBackend)
        .init({
            lng: 'en',
            debug: true,
            ns: ['messages'],
            fallbackLng: 'en',
            resGetPath: '/_locales/__lng__/__ns__.json'
            }, function(err, t) {
              // initialized and ready to go!
              console.log("callback " + err);
        });
```
But the *underscore* of `_locales` is being removed, giving this error:
>GET chrome-extension://eanfcfffakakjhoceeaogbibaadcjijl/locales/en/messages.json net::ERR_FILE_NOT_FOUND

Is there a way to "scape" this underscore? If I change the folder name to `locales` it works, but the objective is let the structure as is...

**Comment by jamuhl** [comment]
your configuration is wrong...https://github.com/i18next/i18next-xhr-backend#backend-options

it's loadPath and must be in backend options

**Comment by McGiverGim** [comment]
Yes, that works now! Thanks!
