### ISSUE TITLE
Using underscores instead of curly braces for variables

### ISSUE THREAD

**Issue by Dubz** [i18next/i18next-xhr-backend#278]
Is there a way I can use underscores rather than curly braces for the loadPath variable?

This used to be how i18next worked (v1.11.1 to be precise). Instead of {{lng}} and {{ns}} it was __lng__ and __ns__. I'm already running dynamic replacements on text wrapped in double curly braces, and it's causing some issues since it is trying to replace lng and ns as well.

I'm not sure if there's an option or way to change this anywhere. I didn't see any options for it.

**Comment by jamuhl** [comment]
there is no separate option - you can toggle https://www.i18next.com/interpolation.html#all-interpolation-options -> prefix / suffix -> but this is for both interpolation in translations and in that urls

**Comment by Dubz** [comment]
Thank you!!!
THis is exactly what I needed and works perfectly!

What exactly did you mean by in translations as well as URLs? I need the URLs to be different, and they work, but I'm not too sure about the translations part. I don't use the library too in depth, it's mostly just to translate a permanent API response to a user friendly message, and have it prepared for internalization if ever needed.

**Comment by jamuhl** [comment]
translations would be https://www.i18next.com/interpolation.html#basic there you would also have to use `__var__` instead of `{{var}}` might you did not have needed that for your messages..

**Comment by Dubz** [comment]
I see what you mean now. I saw an older project using underscores as well. I'll still need them to run off the underscores instead, since they too would be affected by the issue.

Thanks again!!
