### ISSUE TITLE
translation.json isn't loading properly on staging.

### ISSUE THREAD

**Issue by CWSites** [i18next/i18next-xhr-backend#279]
### Environment
- create-react-app
- react-app-rewired
- i18next + react-i18next

### Configuration
```
import i18n from 'i18next';
import Backend from 'i18next-xhr-backend';
import { reactI18nextModule } from 'react-i18next';

i18n
  .use(Backend)
  .use(reactI18nextModule)
  .init({
  		interpolation: {
  			// React already does escaping
  			escapeValue: false
  		},
  		lng: 'en',
      fallbackLng: 'en',
      debug: true,
      react: {
        wait: true
      }
  });

export default i18n;

```

Everything works perfectly on `localhost:3000` however react-router-dom is redirecting my `./locales/en/translation.json` file to my index. I verified that when the code is compiled my `locales` directory is copied over to my `build` directory. 

Any help you could give would be greatly appreciated!

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/issues/431
