### ISSUE TITLE
Load locales from an endpoint which requires credentials

### ISSUE THREAD

**Issue by Kaandriambelo** [i18next/i18next-xhr-backend#282]
Hello guys,

### This is :
- [ ] bug
- [ ] enhancement
- [x] feature-discussion
- [x] question about how to use a feature

### My question is: 
How to load locales from an endpoint which requires credentials ?

### Our configuration
- i18next version: 11.3.3
- i18next-xhr-backend": 1.5.1

### What we did 
This is our i18n configuration:
```
import i18n from 'i18next';
import Backend from 'i18next-xhr-backend';
import { reactI18nextModule } from 'react-i18next';

export const configureI18n = (options = {}) => {
i18n
    .use(
      Backend
    ) 
    .use(reactI18nextModule)
    .init({
      backend: {
        loadPath: options.translationUrl,
        parse: JSON.parse,
        withCredentials: true,
      },

      ns: ['translations'],
      defaultNS: 'translations',

      detection: {
        order: [
          'querystring',
          'cookie',
          'localStorage',
          'navigator',
          'htmlTag',
          'path',
          'subdomain',
        ],

        lookupQuerystring: 'lang',
        lookupCookie: 'lang',
        lookupLocalStorage: 'lang',
      },
    });
  return i18n;
}
```
### Expected information in the documentation of 18next-xhr-backend
In the documentation, we expect to find an example in which we need to send credentials to the endpoint in order to get the locale files.

### Actual
There is the parameter withCredentials but we don't have any clue on how to use.
Unfortunately, we didn't find an example on the net either.

**Comment by jamuhl** [comment]
There is no options to load with credentials. Only the post request can have additional customHeaders.

Guess if you really need this (not sure why one should need to have that - as the client exposes translations anyway) you can easily create a own fork of this backend or a simplified version: https://www.i18next.com/misc/creating-own-plugins#backend

**Comment by Kaandriambelo** [comment]
Thanks for your answer.

To solve the issue, as you mentioned here we added additional customHeaders on our request.
Then, we used the ajax option of backend so that we have this now:
```
backend: {
        loadPath: options.translationUrl,
        parse: JSON.parse,
        ajax: async (url, _, cb) => {
          const { data, request } = await axios.get(url, options.customHeaders);
          cb(data, request);
        },
      }
```
