### ISSUE TITLE
missing files prevent i18next from doing graceful language fallback

### ISSUE THREAD

**Issue by ohgeedubs** [i18next/i18next-xhr-backend#283]
Can we reopen this? (#261)

I'm trying to implement use i18next init with a promise that will resolve once it's completely initialized (so that parts of the app can know the i18next object is initialized- not just immediately after the callback, but also well after). But currently with this issue, it will immediately reject(), even before XHR backend tries out fall back languages.

How can I know when init() has really, truly failed (particularly the backend not being able to find any files)? Currently, if I instead just let it resolve (or use a try/catch) when no appropriate json file could be found, it returns the string keys as fallback for the t() function, and keeps going. On the other hand, if i reject, there's no graceful fallback as described in #261

````js
}, (err, t) => { 
   //init callback
   if (err){
      console.error(err);
      reject('i18next init promise reject');
   }
   resolve('i18next init promise resolve');
});

**Comment by jamuhl** [comment]
guess you just can ignore that error -> there won't be an error if you do not consider failing loading a language is one (you can define your whitelist and load option so i18next will not even try to load languages you do not support).

**Comment by ohgeedubs** [comment]
I do want to allow stuff like "en-US" and "en-GB" to work though with a `nonExplicitWhitelist: true` option, however.

I can ignore the error for now I suppose, but I find it kinda unideal :T

**Comment by jamuhl** [comment]
i guess you provide only `en` so setting `load: 'languageOnly'` will avoid loading en-US including your whitelist for languages you have there should everything loadable therefor having a language not load would be an error.

**Comment by jamuhl** [comment]
then just resolve your promise and treat the error just as a warning...like said...beside failed loads - there is no other error

**Comment by jamuhl** [comment]
or go through the errors and check if one is relevant for your loading demand

**Comment by jamuhl** [comment]
or what behaviour would you like to see?

**Comment by ohgeedubs** [comment]
There should still be some way to see if literally no jsons could be retrieved however.

**Comment by jamuhl** [comment]
what is "half-fail" the callback gets called once and only once with all the language-namespaces in error if not loaded. Do i miss something here? Do you get it called multiple times?

**Comment by ohgeedubs** [comment]
I'm saying that it will run the callback, even when the xhr-backend hasn't "really" failed, as in it hasn't tried the "pure" language yet, which is bad for async.

**Comment by jamuhl** [comment]
what is pure language? the fallback language...

it has - the callback gets called with all languages based on the detected language -> ['en-US', 'en', 'fallbackLng'] - it's done

do you call init twice?

**Comment by jamuhl** [comment]
it queues to load: https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L42

and when loaded if no pendings calls the callback: https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L116

**Comment by ohgeedubs** [comment]
I meant "pure language" as in "en" since that's the term used on gitbook.

Okay, if the callback gets called more than once, basically, the solution is to look for the last error, in which even the fallbackLng json could not be found, right?

I'll do that for now, then.

**Comment by jamuhl** [comment]
if the callback gets called multiple time...there is something wrong on your side...really the init callback gets called only once by design

**Comment by jamuhl** [comment]
https://jsfiddle.net/134uonq0/1/ see yourself - open the console, change language to "de" run again -- loads en, de and callback is only called once

**Comment by ohgeedubs** [comment]
When you said, "the callback gets called with all languages based on the detected language -> ['en-US', 'en', 'fallbackLng'] - it's done"

I assume you meant this flow happened:
1) User has language with "en-US", we only have "en"
2) We call init using detected language of "en-US"
3) Backend tries to find "en-US", it fails and runs the callback
4) Backend tries to find "en", it succeeds, and runs the callback

Anyway, if the callback only gets once, I still can't know when 4) happens, or it fails

**Comment by jamuhl** [comment]
no:

1) User has language with "en-US", we only have "en"
2) We call init using detected language of "en-US"
3) Backends loads both `en-US` and `en`
4) Init callback get called with error en-US could not be loaded

and it gets called once...and only once...

**Comment by ohgeedubs** [comment]
So how can I know that "en" _has_ been loaded?

As opposed to the situation where both "en-US", "en" and the fallbackLng fail?

**Comment by jamuhl** [comment]
en won't be in the error (error is an object containing what gone wrong...not just true)

also if it would have been a temporal issue with loading from backend it would have done 5 retries loading those...so it's actually a language you do not provide

**Comment by ohgeedubs** [comment]
Hi, sorry to reopen again. I don't think I can detect using the error array, since I'm using the i18next-chained-backend which returns "Error: non of the backend loaded data; at loadPosition" errors.

**Comment by jamuhl** [comment]
hm...guess we should add some extended object like  `{ lng, ns, err }` here https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L101 like done on the event https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L84

would that help?

**Comment by ohgeedubs** [comment]
Yea, that would definitely help.

On my end, I can remove the chained backend as a temporary solution.
