### ISSUE TITLE
All namespaces in a single locales bundle file

### ISSUE THREAD

**Issue by olivierpascal** [i18next/i18next-xhr-backend#285]
I would like to load a locales bundle file with all namespaces inside.
I tried to use: `loadPath: '/locales/{{lng}}.json'`

But the lib:
- keep trying loading namespaces by fetching the same url for every namespace, and
- doesn't understand the bundled namespaces inside

I would suggest that if there is no `{{ns}}` to interpolate, consider the JSON as a locales bundle like:
```javascript
{
  "bundle1": {...},
  "bundle2": {...},
}
```

What do you think?

**Comment by jamuhl** [comment]
Would just add more complexity. If you need something like that i would suggest doing something custom using addResourceBundle function.

**Comment by olivierpascal** [comment]
You're right; I'll do this
