### ISSUE TITLE
allowMultiLoading not supported

### ISSUE THREAD

**Issue by olivierpascal** [i18next/i18next-xhr-backend#286]
Tell me if I'm wrong but it seems that allowMultiLoading is not supported. I suggest it to remove it from readme.

**Comment by olivierpascal** [comment]
Just saw [i18next-multiload-backend-adapter](https://github.com/i18next/i18next-multiload-backend-adapter)!

**Comment by jamuhl** [comment]
yes -> multiload adapter is the new way to go...we removed that from the core to reduce complexity

**Comment by karer** [comment]
Please add an appropriate annotation to readme then - I've spent 4 hours exploring why my code with allowMultiLoading stopped working.

**Comment by jamuhl** [comment]
@karer support was not removed in the backend implementation - it was removed there...so you upgraded your i18next from <= v10.x.x to 11.x.x

-> https://www.i18next.com/misc/migration-guide#v-10-x-x-to-v-11-0-0
-> https://github.com/i18next/i18next/blob/master/CHANGELOG.md#1100---1111-fixing-version-mismatch-cdnjs---npm

I'm sorry for your time wasted.
