### ISSUE TITLE
Documentation on POST for addPath

### ISSUE THREAD

**Issue by pinkynrg** [i18next/i18next-xhr-backend#291]
I get the i18next-xhr-backend working and it is calling by backend properly. 

I'm getting a weird payload such as the following: 

```
{'navbar_title': ['navbar_title'], '_t': ['Tue Dec 11 2018 15:04:06 GMT-0600 (Central Standard Time)']}
```

I don't understand why I'm not getting something more like the following:

```
{key: 'navbar_title'. _t: ['Tue Dec 11 2018 15:04:06 GMT-0600 (Central Standard Time)']}
```

It looks like a single POST request can be made for multiple items?
Why the navbar_title both in the key of the object and in the value? 
Is there any documentation on how the API works though?

**Comment by jamuhl** [comment]
looks like something is intercepting the xhr?!?
