### ISSUE TITLE
ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by desmeit** [i18next/i18next-xhr-backend#293]
```
                                i18next.init({
		 			debug: true,
					lng: 'de-DE',
					load: "currentOnly", //OR load: 'unspecific'
					fallbackLng: 'de',
					backend: {
					  loadPath: 'locales/{{lng}}/{{ns}}.json',
                                       }
```

I get access to my file locales/de/translation.json but I'm wondering why I get the following error in addition:

`GET ... /locales/de-DE/translation.json net::ERR_FILE_NOT_FOUND`

I have a fallback to "de", why does it still want to access the file 'de-DE'?

**Comment by jamuhl** [comment]
load: 'languageOnly' is what you want

**Comment by desmeit** [comment]
Perfect, thanks again. But where could I find such infos? Are there additional docs?

**Comment by jamuhl** [comment]
https://www.i18next.com/overview/configuration-options#languages-namespaces-resources

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:

**Comment by desmeit** [comment]
Sorry, still one question. languageOnly is working but if there is not "de" File, I get the ERR_FILE_NOT_FOUND message. Is that normal or what I'm doing wrong?

**Comment by jamuhl** [comment]
if the file does not exist that warning is normal...and can be ignored.

**Comment by jamuhl** [comment]
if you want completely get rid off that use the whitelist option: https://www.i18next.com/overview/configuration-options#languages-namespaces-resources

**Comment by desmeit** [comment]
very good support. thanks
