### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by VincentLanglet** [i18next/i18next-xhr-backend#295]
@jamuhl 
`I18next` and `I18next-xhr-backend` have `index.d.ts` but the `I18next-xhr-backend` types are on DefinitivelyTyped. What about adding back here for more homogeneity ?

This module does not change a lot, so you won't need to update them frequently.
And you now have nice collaborator like @rosskevin to help you about typescript support.

**Comment by jamuhl** [comment]
Feel free to provide a PR

**Comment by VincentLanglet** [comment]
@jamuhl Done : https://github.com/i18next/i18next-xhr-backend/pull/296
