### ISSUE TITLE
Cannot import BackendOptions from namespace in TypeScript

### ISSUE THREAD

**Issue by michaelbull** [i18next/i18next-xhr-backend#299]
I'm using the typescript definitions provided by the library itself, not the ones on `@types`, and am trying to import the `BackendOptions` interface (so I can strongly type my options). Example:

```typescript
import * as I18NextXhrBackend from 'i18next-xhr-backend';

let options: I18NextXhrBackend.BackendOptions = {
    loadPath: '{{lng}}/{{ns}}'
};
```

However this produces the following error:

```
TS2694: Namespace '"node_modules/i18next-xhr-backend/index"' has no exported member 'BackendOptions'.
```

**Comment by jamuhl** [comment]
@VincentLanglet ideas?

@michaelbull i do not maintain the types myself - so hopefully some other typescript user can help

**Comment by VincentLanglet** [comment]
@michaelbull Hi !

```
import Backend, { I18NextXhrBackend } from 'i18next-xhr-backend';
```
Does work, so you should write
```
import * as Foo from 'i18next-xhr-backend';

let options: Foo.I18NextXhrBackend.BackendOptions = {
    loadPath: '{{lng}}/{{ns}}'
};
```

I agree, it's not the best

**Comment by michaelbull** [comment]
Ah, that's how you do it. Thanks for your help guys.
