### ISSUE TITLE
Pass language and namespace(s) to custom ajax method

### ISSUE THREAD

**Issue by jgornick** [i18next/i18next-xhr-backend#300]
In order to prevent extraneous requests, I would like to short circuit requests for languages and/or namespaces I know won't exist. i18next will cause a request to load the default `translate` namespace, but I want to prevent that request to my backend so that only whitelisted languages/namespaces are requested.

Thoughts?

**Comment by jamuhl** [comment]
namespaces are only loaded if in namespaces or requested explicitely

languages can be set using whitelist, fallbackLng: false, ...

https://www.i18next.com/overview/configuration-options#languages-namespaces-resources

**Comment by jgornick** [comment]
@jamuhl Probably good point and we're doing a withNamespace()(...) somewhere which is going to fallback to `translate` as the namespace.
