### ISSUE TITLE
addPath doesn't seem to be working even with saveMissing:true

### ISSUE THREAD

**Issue by blunatic** [i18next/i18next-xhr-backend#303]
Maybe I'm missing something, but I've got the following and I'm not seeing how to trigger missing keys:

```

import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import XHR from 'i18next-xhr-backend';

i18n
  .use(XHR)
  // pass the i18n instance to react-i18next.
  .use(initReactI18next)
  .init({
    lng: 'en',
    fallbackLng: 'en',
    debug: true,

    saveMissing: true, // send not translated keys to endpoint
    nonExplicitWhitelist: true,

    // have a common namespace used around the full app
    ns: ['discover', 'groups'],
    defaultNS: 'discover',

    interpolation: {
      escapeValue: false // not needed for react as it escapes by default
    },

    backend: {
      // path where resources get loaded from, or a function
      // returning a path:
      // function(lngs, namespaces) { return customPath; }
      // the returned path will interpolate lng, ns if provided like giving a static path
      loadPath: '/locales/{{lng}}/{{ns}}.json',

      // path to post missing resources
      addPath: '/locales/add/{{lng}}/{{ns}}',
      
      // allow cross domain requests
      crossDomain: false,

      // allow credentials on cross domain requests
      withCredentials: false,
    }
  });
;

export default i18n;
```

Nothing ever seems to be written to `/locales/add/*` despite some of the keys in `en.json` not having translations in `de.json` or `es.json`. I had noticed a few other issues on this project around `saveMissing` needing to be set to true, but even with that in place I'm not seeing any POSTs happen.

**Comment by jamuhl** [comment]
You're using webpack devserver serving statics from your public folder. To use the saveMissing feature you need a "real" server able to post data to an endpoint that handles that data.

Eg. i18next-express-middleware https://github.com/i18next/i18next-express-middleware can do this

Or our service https://locize.com has that supported.

**Comment by blunatic** [comment]
@jamuhl late reply, but I was able to figure out a solution to this using a custom language translation. Thanks for the clarification, I'll go ahead and close this.
