### ISSUE TITLE
Is bundle-loader necessary for use with webpack?

### ISSUE THREAD

**Issue by MareoRaft** [i18next/i18next-xhr-backend#305]
To me, the heading in the README "Usage with webpack's bundle loader instead of using xhr requests" isn't clear about whether it is *necessary* to use the bundle-loader when using webpack or not.

If this is necessary when using webpack in order to get things to work, I would suggest changing the heading to "How to use with webpack" and in the explanation say that it is necessary to use the bundle-loader.

Sorry if this is nitpicky, but I'm having a lot of trouble setting things up.

So if I use the bundle-loader, will the library no longer be using XHR requests?  If that's the case, what type of requests will be used instead?

**Comment by jamuhl** [comment]
bundle-loader will replace xhr - will drop that line completely...it's unreleated and was added on request. either people search for a xhr backend or webpack related to bundle translations.

**Comment by MareoRaft** [comment]
I don't think that saying less increases clarity.  If people using Webpack should probably be using a different approach, then it's good to have that information available or referenced.

I think an underlying issue is that certain `i18next` tutorials point people towards this repo.  So if I'm following the tutorial at https://react.i18next.com/, it includes using i18next-xhr-backend.  But most react projects use Webpack, as `create-react-app` gives you Webpack set up out of the box.

**Comment by jamuhl** [comment]
No users using webpack should not take a different approach...at least not as best practice...it's a option - like everything in i18next it's about having the freedom of doing things like you want - with as less opinionated fixed you need to do it the i18next way.

If you read more about i18next (not react-i18next) you see i18next uses a plugin system...so loading of translations can be done in many ways...eg. node.js -> file, remote, ..., browser -> xhr, services, ...

https://www.i18next.com/overview/plugins-and-utils#backends

The xhr-backend is just the most used option, like the browser-languagedetector the most used option for language detection (but not the only one)

And what is all the talk about webpack...webpack is a module bundler...nothing more - nothing less...
