### ISSUE TITLE
Suspense error

### ISSUE THREAD

**Issue by MareoRaft** [i18next/i18next-xhr-backend#306]
I have i18next working well without i18next-xhr-backend.  When I add in i18next-xhr-backend, I encounter the error

    Error: withI18nextTranslation(App) suspended while rendering, but no fallback UI was specified. Add a <Suspense fallback=...> component higher in the tree to provide a loading indicator or placeholder to display. in withI18nextTranslation(App) (at src/index.js:21) in Provider (at src/index.js:18)

Intererestingly, the error occurs **both** when I **do** and **do not** wrap my

    			<div className="App">
    				{t('welcome', )}
    			</div>

component jsx in `<Suspense fallback={<Spinner />}>` ... `</Suspense>` tags.

My i18next-xhr-backend setup follows the README with webpack option exactly as it asks: (`import detector from 'i18next-browser-languagedetector';` import, `function loadLocales ... }` function verbatim, `.use(backend)` as the first thing appended to i18next object, and `backend: {loadPath: '{{lng}}', parse: (data) => data, ajax: loadLocales}` options in the i18next.init).

Thanks and sorry for the trouble.

**Comment by MareoRaft** [comment]
I think the issue may be that the suspense tags are in the SAME component that is wrapped with `withTranslation` instead of a higher one.  I will try moving the suspense tags into index.js instead.

**Comment by MareoRaft** [comment]
That worked.  I used

	import React, {Component, Suspense} from 'react';

	<Suspense fallback='loading'>
			<div className="App">
				<Layout />
			</div>
	</Suspense>

**Comment by jamuhl** [comment]
Yes...Suspense "catch" needs to be higher in the order

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
