### ISSUE TITLE
Multiloading with i18next-express-middleware

### ISSUE THREAD

**Issue by Badji** [i18next/i18next-xhr-backend#307]
Hi,
I am triying to setup multiloading, without success.

Client:
    "i18next": "^15.0.9",
    "i18next-browser-languagedetector": "^3.0.1",
    "i18next-multiload-backend-adapter": "^0.1.1",
    "i18next-xhr-backend": "^2.0.1",
    "react-i18next": "^10.6.1",

Server:
    "i18next": "^15.0.9",
    "i18next-express-middleware": "^1.7.3",
    "i18next-node-fs-backend": "^2.1.2",

The issue is that "i18next-xhr-backend" uses "+" as language and namespace separator in its request [link](https://github.com/i18next/i18next-xhr-backend/blob/50eae0285475891090fbcae7d151fdad53717174/src/index.js#L33)  while on the serverside "i18nextMiddleware.getResourcesHandler()" expect spaces as separators [link](https://github.com/i18next/i18next-express-middleware/blob/ebc9dc4d41337f94da27506df240cc00854231b5/src/index.js#L100) both separators are hardcoded and can't be changed

Can someone help ?

**Comment by jamuhl** [comment]
Was this solved? Used to work in the past....

**Comment by Badji** [comment]
Yes my bad sorry
