### ISSUE TITLE
missingKeyHandler is called even when translations exist if I use a custom backend.ajax

### ISSUE THREAD

**Issue by tonix-tuft** [i18next/i18next-xhr-backend#308]
Hello,

I am experiencing an issue with the following configuration (using `i18next-react` and this backend plugin):

```
i18n
   .use(initReactI18next)
   .use(i18nextXHRBackend)
   .init({
      lng,
      fallbackLng: defaultLng,
      debug,
      ns: ['common'],
      defaultNS: 'common',
      interpolation: {
         escapeValue: false
      },
      saveMissing: true,
      missingKeyHandler,
      backend: {
         loadPath: loadPathBaseUrl + '/i18n/{{lng}}/{{ns}}.json',
         ajax: loadLngAJAX,
         crossDomain: true
      }
   });
export default i18n;
```
If I use a custom `missingKeyHandler` and a custom `backend.ajax` callback, `missingKeyHandler` gets fired even when translations exist and are loaded (I see messages in the console if `debug` is `true` and my `missingKeyHandler` is called).

If I comment this line out:

```
...
//ajax: loadLngAJAX,
...
```
Everything works and `missingKeyHandler` is not fired (as it should be even when using a custom `ajax` with this backend plugin).

Do you think this is a bug or is there a reason why I am experiencing this behaviour?

Thank you for your attention.

**Comment by jamuhl** [comment]
my guess...translations get not correctly loaded when you use your custom ajax - only reason why it works if you remove that -> do you get the backend loaded messages?

**Comment by tonix-tuft** [comment]
Yes,

I can see the messages, look:

![Screen Shot 2019-04-23 at 18 54 32](https://user-images.githubusercontent.com/10134421/56600711-a326c580-65f9-11e9-9c74-328b47a4e225.png)

if I open the `Network` tab in the console I see them.
However, when both `backend.ajax` and `missingKeyHandler` exist, `missingKeyHandler` is called even if (as shown before) my translations are loaded and those keys exist:

![Screen Shot 2019-04-23 at 18 54 48](https://user-images.githubusercontent.com/10134421/56600918-221bfe00-65fa-11e9-8aa3-cc0347d2ff46.png)

![Screen Shot 2019-04-23 at 18 54 59](https://user-images.githubusercontent.com/10134421/56600967-38c25500-65fa-11e9-9648-564cc0dfe2bc.png)


The point is that I have implemented my missing key handling logic in `missingKeyHandler `,
and it worked (as soon as I save a missing key, the next time `i18next` does not fire the `missingKeyHandler` again if I reload the page because the translation are there from that point).

Then I noticed that I also need to laverage `backend.ajax` because I build my JSON translation URIs server-side with a version to bypass the browser's cache (otherwise I experienced old translations being loaded from the browser's cache if I just used `backend.loadPath: loadPathBaseUrl + '/i18n/{{lng}}/{{ns}}.json'`).

As soon as I implemented `backend.ajax` and left my `missingKeyHandler`, I started to notice that `i18next` keeps on calling my `missingKeyHandler` even when the translations are there.

This makes me think that this could be a bug.

Both `backend.ajax` and `missingKeyHandler` coexist in my init options, but I would not expect that `missingKeyHandler` gets called many times even after I have already handled the missing keys and they are loaded.

Are you able to reproduce the same inconsistency?

**Comment by tonix-tuft** [comment]
Mmm...,

maybe it's the way I handle the server's response.

Within the `backend.ajax` callback (`loadLngAJAX`), after doing the AJAX request I call the `callback` parameter (the third one provided by `i18next`):

```...
      callback(data, {
         status
      });
      ...
```

I debugged this code and `data` is the parsed JSON (JS Object):

```
{
    "unknownAction": "@unknownAction@",
    "permissionDenied": "@permissionDenied@",
    "translateThis": "@translateThis@",
    "permissionDeniedOrSessionExpired": "@permissionDeniedOrSessionExpired@",
    "wrongRequestParameters": "@wrongRequestParameters@",
    "sessionExpired": "@sessionExpired@"
}
```

While the second parameter is an object with the `status` property (which in my case has a value of `200`).

Am I calling the callback correctly?

**Comment by tonix-tuft** [comment]
I was able to resolve...

I added a dummy `backend.parse` callback which just returns the `data` (because I have noticed that it gets called with the data I parsed in the `backend.ajax` callback).

```
...
i18n
   .use(initReactI18next)
   .use(i18nextXHRBackend)
   .init({
      lng,
      fallbackLng: defaultLng,
      debug,
      ns: ['common'],
      defaultNS: 'common',
      interpolation: {
         escapeValue: false
      },
      saveMissing: true,
      missingKeyHandler,
      backend: {
         loadPath: loadPathBaseUrl + '/i18n/{{lng}}/{{ns}}.json',
         ajax: loadLngAJAX,
         parse: (data) => data, // <----- Added this line and everything started to work again.
         crossDomain: true
      }
   });
export default i18n;
```

This `backend.parse` shouldn't be needed though, as I already parsed the data in `backend.parse`,
don't you agree?

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-xhr-backend/blob/master/src/index.js#L50 -> parse does JSON.parse

**Comment by tonix-tuft** [comment]
Yes, but I needed to override it with a dummy hook which just return the value because as I understood `parse` is called by the `callback` with the translation data passed to it.

Otherwise I am experiencing the misleading behaviour above, at least it works now.

**Comment by jamuhl** [comment]
Yes - not sure what happens - but in the end the code is dead simple...ajax and missingHandler have nothing todo with each other only if the ajax call somehow does not provide the data in correct format for parse (which is a JSON.parse) to succeed. That is what fails currently and your parse dummy "fixes" - the underlying problem still is in your ajax implementation.

But like you say - works with both - so: If it's ok for you - it's ok for me 😁
