### ISSUE TITLE
Add new translation language

### ISSUE THREAD

**Issue by tiagoporto** [i18next/i18next-xhr-backend#310]
Hello, I'm having the following issue

I have the languages files inside the folder locales/{{lang}}/{{ns}}.json

The settings
```js
import * as i18next from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import I18nXHR from 'i18next-xhr-backend';

 i18next
  .use(I18nXHR)
  .use(LanguageDetector)
  .init({
    detection: {
      order: ['querystring', 'navigator', 'htmlTag'],
      lookupQuerystring: 'lang'
    },
    whitelist: ['en'],
    nonExplicitWhitelist: true,
    load: 'languageOnly',
    ns: ['app'],
    defaultNS: 'app',
    keySeparator: '.',
    lowerCaseLng: true,
    interpolation: {
      escapeValue: false,
      formatSeparator: ','
    },
    react: {
      wait: true
    },
    backend: {
      loadPath: '/locales/{{lng}}/{{ns}}.json',
      ajax: async (
        url: string,
        options: any,
        callback: (data: string, status: any) => void,
        data: any
      ) => {
        const res = await fetch(url, { cache: 'no-cache' });
        const json = await res.json();
        callback(JSON.stringify(json), { status: res.status });
      }
    }
  });
```

With "en" the application works, but in production we need add another translation folder to support more languages, example "es", after `i18n.changeLanguage('es'),` the `i18next-xhr-backend` doesn't request the files, and the application shows the keys.

I need to add the translations file without changing the code in production to update the whitelist.

Is it possible?

Thanks

**Comment by jamuhl** [comment]
Either remove the whitelist if you can't update that...or use our https://locize.com -> the backend gives you all languages filled with percentage completed so you can set whitelist dynamically as needed...

**Comment by tiagoporto** [comment]
@jamuhl thanks for your quick reply.

I tried your suggestion and removed the whitelist from settings, but now the **i18next-xhr-backend** return a different error.

I'm using the **i18next-browser-languagedetector**, so when the application is loaded the i18n receive the language from my browser, example `pt-BR`, but I don't have the translation to this language. So, I added 
```js
fallbackLng: 'en'
```
Even with these settings, the **i18next-xhr-backend** try to access the `pt-BR` files and return the error

```js
SyntaxError: Unexpected token < in JSON at position 0
```

I think the whitelist it´s necessary to prevent the request.

Which is the right way to set whitelist dynamically as you suggested?

**Comment by jamuhl** [comment]
Normally a request to pt-BR (not having that file) would return a 400 (not found) which would be ok...seems your backend just returns some html?

**Comment by tiagoporto** [comment]
You are right, the backend returns an HTML.

Just updating the ajax function fixed,

```js
backend: {
  loadPath: '/locales/{{lng}}/{{ns}}.json',
  ajax: async (
    url: string,
    options: any,
    callback: (data: string, status: any) => void,
    data: any
  ) => {
     try {
        const res = await fetch(url, { cache: 'no-cache' });
        const json = await res.json();
        callback(JSON.stringify(json), { status: res.status });
     }
     catch (error) {
        callback(null, { status: 404 });
     }
  }
}
```

Thank you @jamuhl

**Comment by jamuhl** [comment]
f you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
