### ISSUE TITLE
[Q]React native loadPath

### ISSUE THREAD

**Issue by sabbin** [i18next/i18next-xhr-backend#317]
I'm trying to implement the `i18next` in my current react-native app.

On the `init` function I have the following options

```js
{
    fallbackLng: 'en',
    debug: true,

    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
    },

    backend: {
      loadPath: '/translations/{{lng}}/{{ns}}.json',
    }
}
```

The folder `translations` is in the root of the application. 

The issue is that the build, the android build in my case does not find the specified folder and I get the following error

> i18next::backendConnector: loading namespace translation for language en failed failed parsing /translations/en/translation.json to json

Where should the translations folder be placed in order for the build to be able to access it? I could't find an example somewhere where the actual translations to be loaded from a file and not from `resources` param in the `options` object

**Comment by jamuhl** [comment]
XHR ---> load via XHR -> while browser will load relative for react native you will have to set a full qualified url to your server

or import translations from inside the bundle project and add them on init: https://github.com/i18next/react-i18next/blob/master/example/react-native/App.js#L20

**Comment by sabbin** [comment]
@jamuhl Thank you for your response... due to the fact that I test the app in the Android Studio virtual device I think I will go with the import in the `resource` object. In react I could use them relative to the browser but in the virtual device I think that there is some other logic.

I will go with the second option

**Comment by AlbinCederblad** [comment]
> 
> 
> @jamuhl Thank you for your response... due to the fact that I test the app in the Android Studio virtual device I think I will go with the import in the `resource` object. In react I could use them relative to the browser but in the virtual device I think that there is some other logic.
> 
> I will go with the second option

How did you solve it?

**Comment by jamuhl** [comment]
@AlbinCederblad Not done react-native for long time...can't remember there where any issues. But we also loaded from a server and cached the translations using some async storage.

**Comment by adrai** [comment]
https://www.i18next.com/how-to/caching#react-native-caching-with-asyncstorage
