### ISSUE TITLE
"No inputs were found in config file" - tsconfig typo?

### ISSUE THREAD

**Issue by ThomasVandenbon** [i18next/i18next-xhr-backend#323]
In Visual Studio Code I'm getting the following warning:
`No inputs were found in config file '..../node_modules/i18next-xhr-backend/tsconfig.json'. Specified 'include' paths were '["./indext.d.ts","./test/**/*.ts*"]' and 'exclude' paths were '[]'.ts`

This looks like it might be a typo, as "index**t**.d.ts" should probably be "index.d.ts".

**Comment by adrai** [comment]
will be included in the next version

**Comment by jamuhl** [comment]
published in i18next-xhr-backend@3.1.2
