### ISSUE TITLE
Request language dev

### ISSUE THREAD

**Issue by alirezaseif28** [i18next/i18next-xhr-backend#334]
hi.
I went ahead with the documentation and implemented it according to the following code
` i18next.use(Backend).init({
        backend: {
            // for all available options read the backend's repository readme file
            loadPath: '/Scripts/locales/{{lng}}/{{ns}}.json'
        }
    });`

When I look at server-side requests, I see that these files are in demand.

localhost/Scripts/locales/en/translation.json
localhost/Scripts/locales/de/translation.json
and 
localhost/Scripts/locales/dev/translation.json
.
I wanted to know what this last request is for, do I have to make adjustments?

thank you

**Comment by jamuhl** [comment]
Von meinem iPhone gesendet

**Comment by jamuhl** [comment]
the last one is from the default set `fallbackLng` which per default is set to a pseudo language dev (developer english 😁)...

you can set fallbackLng to the main language you like to show if detected language is not supported

https://www.i18next.com/principles/fallback#fallback-language

**Comment by alirezaseif28** [comment]
Thank you.
