### ISSUE TITLE
category files

### ISSUE THREAD

**Issue by alirezaseif28** [i18next/i18next-xhr-backend#338]
hi.
I went ahead with the documentation and implemented it according to the following code
`i18next.use(Backend).init({ backend: { // for all available options read the backend's repository readme file loadPath: '/Scripts/locales/{{lng}}/{{ns}}.json' } });`

How do I have multiple files in multilingual folders? For example, I have a file Caption and a validation file on my backend.
 How does it fit into the language folders with the same category?
Thanks.

**Comment by jamuhl** [comment]
ns -> is what you call category

**Comment by alirezaseif28** [comment]
yes.ok
I have a translation file
I want to have some  translation files.include caption file and validation file and etc.
Thanks

**Comment by jamuhl** [comment]
Nesting files...like some magic scss stuff...?

You can have multiple files and load / use them...but we do not have some build time include mechanism...

**Comment by alirezaseif28** [comment]
thanks.
in line 
` loadPath: '/Scripts/locales/{{lng}}/{{ns}}.json'`
When I look at server-side requests, I see that these files are in demand.

localhost/Scripts/locales/de/translation.json
but i have two files.
translation.json
validation.json
and why not get validation.json file?
thanks

**Comment by jamuhl** [comment]
eventual reading the docs: https://www.i18next.com/principles/namespaces#sample

**Comment by alirezaseif28** [comment]
Great
Best regards
