### ISSUE TITLE
Issues with loading translations from express endpoint

### ISSUE THREAD

**Issue by iamchathu** [i18next/i18next-xhr-backend#343]
I'm using express middleware to setup a language server endpoint and use XHR backend to pull data for react application.

server code 

```ts
import i18next from 'i18next';
import Backend from 'i18next-node-fs-backend';
import i18nextMiddleware from 'i18next-express-middleware';
import express from 'express';
import bodyParser from 'body-parser';

i18next.use(Backend).init({
  preload: ['en', 'si', 'zh'],
  lowerCaseLng: true,
  backend: {
    loadPath: './locales/{{lng}}/{{ns}}.json',
    addPath: './locales/{{lng}}/{{ns}}.missing.json',
    jsonIndent: 4,
  },
  load: 'all',
  lng: 'en',
  fallbackLng: 'en',
  ns: ['common'],
  debug: true,
  saveMissing: true,
});

const PORT = 3003;
const app = express();

app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

app.use(
  i18nextMiddleware.handle(i18next, {
    removeLngFromUrl: false,
  }),
);

app.post(
  '/locales/add/:lng/:ns',
  (req, res, next) => {
    console.log('add String', req.body);
    next();
  },
  i18nextMiddleware.missingKeyHandler(i18next),
);

app.get(
  '/locales/resources.json',
  i18nextMiddleware.getResourcesHandler(i18next),
);

app.listen(PORT, () => console.log(`Translation server listing on ${PORT}`));
```

And my client side code looks like 

```ts
import i18n from 'i18next';
import Backend from 'i18next-chained-backend';
import XHR from 'i18next-xhr-backend';
import LocalStorageBackend from 'i18next-localstorage-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';

i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    ns: ['common'],
    fallbackLng: {
      'en-US': ['en'],
      default: ['en'],
    },
    fallbackNS: 'common',
    defaultNS: 'common',
    preload: ['en'],
    lng: 'en',
    debug: process.env.NODE_ENV === 'development',
    backend: {
      backends: [LocalStorageBackend, XHR],
      backendOptions: [
        {
          prefix: 'i18n_res_',
          expirationTime: 1000,
        },
        {
          loadPath: 'http://localhost:3003/locales/resources.json?lng={{lng}}&ns={{ns}}',
          addPath: 'http://localhost:3003/locales/add/{{lng}}/{{ns}}',
          allowMultiLoading: true,
          saveMissing: true,
          load: 'currentOnly',
        },
      ],
    },
    interpolation: {
      escapeValue: false,
    },
    react: {
      wait: true,
      useSuspense: true,
    },
    detection: {
      //
    },
  });

export default i18n;
```

I'm getting client side logs as

```log
i18next::backendConnector: loaded namespace common for language en {en: {…}}en: common: {item: "Item", item_plural: "Items", date: "Date", date_plural: "Dates", from_date: "From date"}__proto__: Objecti18nStamp: 1583945344386__proto__: Object
i18next.js:27 i18next: languageChanged en
i18next.js:27 i18next: initialized {debug: true, initImmediate: true, ns: Array(1), defaultNS: "common", fallbackLng: {…}, …}
i18next.js:27 i18next::translator: missingKey en common item item
```

But if I set in options of react

```ts
resources: {
     en: { common: { item: 'ITEm', login: 'LOgIN' } },
 },
```

It works. But even though it loads from the server and save to local storage too but get error saying `missingKey`

**Comment by jamuhl** [comment]
The missing part -> regular usage: serve the translations as static content (one file per lng-namespace: `/locales/{{lng}}/{{ns}}.json`

Using multiload -> needs also https://github.com/i18next/i18next-multiload-backend-adapter to work

**Comment by iamchathu** [comment]
@jamuhl Thanks for quick reply. Can this use with Chained backend?

**Comment by jamuhl** [comment]
Yes...might be just a little ugly to set the configurations right (all the nested options)

**Comment by ne0c0de** [comment]
this is my client code:
```
i18next
      .use(i18nextXHRBackend)
      .init({
        fallbackLng: 'tr_TR',
        lng: 'tr_TR',
        debug: true,
        ns: ['translation'],
        defaultNS: 'translation',
        whitelist: ['tr_TR', 'en_US'],
        preload: ['tr_TR', 'en_US'],
        backend: {
          allowMultiLoading: true,
          loadPath: '/darkside/locales/resources.json?lng={{lng}}&ns={{ns}}'
        }
      }, function(err, t) {
        if (err) {
          console.log('err: ', err)
        }
        console.log('i18next.t: ', i18next.t('studentOf'))
      })
```

where my client side is using reguler nodeJS with PUG view engine.

the console output show that language is loaded before calling t function.

here's the console debug output:

```
i18next::backendConnector: loaded namespace translation for language tr_TR
i18next: languageChanged tr_TR
i18next: initialized
i18next::translator: missingKey tr_TR translation studentOf studentOf
i18next.t:  studentOf
```

even if I added 
```
react: {
          wait: true,
          useSuspense: false,
        }
```

options it didn't change anything.

also on browser console I entered this command:

```
i18next.getResourceBundle('tr_TR', 'translation')
```

this is shows me the translations loaded correctly because it's giving the translations as object

What am I doing wrong?

**Comment by ne0c0de** [comment]
I put some debug lines into the i18next main javascript file above the missing log line like this:

```
 if (usedKey || usedDefault || updateMissing) {
            console.log(this)
            this.logger.log(updateMissing ? 'updateKey' : 'missingKey', lng, namespace, key, updateMissing ? options.defaultValue : res);
```

after that i saw that translations loaded incorrectly:

https://imgur.com/a/1PhaWsj

so if I try to get translation like that:

```
console.log('i18next.t: ', i18next.t('tr_TR.translation.studentOf'))
```

it's getting the translation.

so I changed allowMultiLoading: true to false but it didn't reflect

In my network console I see that locales are loading like this:

http://127.0.0.1/locales/resources.json?lng=tr_TR&ns=translation

the response like this:

https://imgur.com/a/mV1qFJ5

(where I'm using https://github.com/i18next/i18next-express-middleware to get translations)

this is my backend router line:

```
router.get('/locales/resources.json', i18nextMiddleware.getResourcesHandler(__lang));
```

I think I missing some trick but couldn't find it yet

**Comment by jamuhl** [comment]
https://imgur.com/a/mV1qFJ5 is multiload format not supported for a long time -> use https://github.com/i18next/i18next-multiload-backend-adapter on client or serve non multiload format for translations...(not having `tr_TR: { translation: { .... } }`)

also, use languages with `-` -> tr-TR (underline form is not supported)

most of your issues comes from using outdated stuff like multiloadAllowed in backend options or wait: true in react options --- guess you're mixing a lot of outdated samples and created a big mess ;)

**Comment by ne0c0de** [comment]
I tried to use https://github.com/i18next/i18next-multiload-backend-adapter but it didn't allow i18next to initialize :)

So I give up to use https://github.com/i18next/i18next-express-middleware (which is an official middleware of the i18next team) 

Actually i were used the example codes on readme files of the official github pages but none of them work correctly togetger.

For further use here's my own middleware which is a single line code:

```
router.get('/locales/resources.json', mwWithoutCache, (req, res, next) => { res.json(__lang.getResourceBundle(req.query && req.query.lng ? req.query.lng : 'tr_TR', req.query && req.query.ns ? req.query.ns : 'translation')) })
```

this is giving me the correct output for i18nextXHRBackend where I can use it on client side.

this is my final code for client side:

```
i18next
      .use(i18nextXHRBackend)
      // .use(i18nextXHRBackend)
      .init({
        fallbackLng: 'tr_TR',
        lng: 'tr_TR',
        debug: true,
        ns: ['translation'],
        defaultNS: 'translation',
        whitelist: ['tr_TR', 'en_US'],
        preload: ['tr_TR', 'en_US'],
        saveMissing: false,
        backend: {
          loadPath: '/darkside/locales/resources.json?lng={{lng}}&ns={{ns}}',
        }
      }, function(err, t) {
        if (err) {
          console.log('err: ', err)
        }
        console.log('t: ', t('studentOf'))
      })
```

I hope it will help someone in the future

**Comment by jamuhl** [comment]
the i18next-express-middleware is not about serving translations to client but using i18next in express / templates...

glad you figured out a solution that worked for you...
