### ISSUE TITLE
How to read from json file

### ISSUE THREAD

**Issue by uendar** [i18next/i18next-xhr-backend#353]
I am trying to get my translation from and api endpoint and the code i have is:

```
i18n

  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    fallbackLng: 'it-IT',
    debug: false,
    keySeparator:false,
 
    interpolation: {
      escapeValue: false, 
    },
    
    react: {
      defaultTransParent: 'div', 
      wait: true,
    },

    request: getTranslations('en')
   
  });
```

The function getTransaltions() returns json data. Now my question is what i need other in configuration to make it work and read my translations in code. 

for example  ` {t('dashboard.title')}`

**Comment by adrai** [comment]
This module is deprecated, please have a look at i18next-http-backend and this example: https://github.com/i18next/i18next-http-backend/blob/master/example/node/app.js

I think you don't need to define the request option at all...
