### ISSUE TITLE
i18next compatibility - MultiReadCallback 

### ISSUE THREAD

**Issue by DevronB** [i18next/i18next-xhr-backend#357]
I'm using this library with the latest version of i18next. It seems there is a small compatibility issue with the typing's.

can/should the following changes be made to line up with i18next typings please?

import { BackendModule, ReadCallback, _**MultiReadCallback**_ } from 'i18next';

readMulti(languages: string[], namespaces: string[], callback: _**MultiReadCallback**_): void;

**Comment by adrai** [comment]
i18next-xhr-backend is deprecated, use [i18next-http-backend](https://github.com/i18next/i18next-http-backend) instead

**Comment by DevronB** [comment]
Ok thanks, I did try the http-backend but I use requireJs and it had issues with it trying to require the file from lib, like getFetch.cjs

I don’t understand enough to know why, but these files are not bundled with the min file. Am I missing something obvious?

Cheers
Devron

**Comment by adrai** [comment]
Would be nice if you could create a setup with requirejs, so we can investigate...

Maybe requireJs needs this output? https://github.com/i18next/i18next-http-backend/blob/master/i18nextHttpBackend.js

Or you need to require it like this: `require('i18next-http-backend/cjs')`

**Comment by DevronB** [comment]
Thanks, importing the js file directly resolves the issue.
