### ISSUE TITLE
Webpack build warning

### ISSUE THREAD

**Issue by kylehood** [i18next/i18next-xhr-backend#70]
https://github.com/i18next/i18next/issues/477 

I am running into an identical issue with this plugin when bundling with Webpack. I will take the solution from the referenced issue and open a pull request for the fix.

Thanks!

**Comment by jamuhl** [comment]
should already be addressed in v0.4.0...

i hope...export is new lib/index.js

**Comment by kylehood** [comment]
Oh perfect! I ran into this yesterday, and I didn't notice it was fixed already this morning. Awesome timing! :smile: 

Upgraded to v0.4.0 and the warning is gone. Thanks!

**Comment by jamuhl** [comment]
haha...yes...was not even planned for today...but perfect timing
