### ISSUE TITLE
module import error while working with Rollup

### ISSUE THREAD

**Issue by fengshuo** [i18next/i18next-xhr-backend#73]
Hi,

I am using rollup to bundle i18next, i18next-xhr-backend, jquery-i18next with other ES6 modules, after rollup bundled these files successfully, browser logged an error message from *i18next-xhr-backend/lib/index.js*: `utils.defaults is not a function`.

I checked the source file, it seems that this line doesn't work as expected: `var _utils = require('./utils');` ,  I tried to change it to non-relative paths: `var _utils = require('utils');`, then it works. I am not sure if it's caused by rollup plugins as described [here](https://github.com/rollup/rollup/issues/547), because no error message came from other packages (i18next, jquery-i18next), they are bundled in the same manner.   

Below is the rollup config:  

```
import babel from 'rollup-plugin-babel';
import commonjs from 'rollup-plugin-commonjs';
import includePaths from 'rollup-plugin-includepaths';
import nodeResolve from 'rollup-plugin-node-resolve';

var includePathOptions = {
  paths: ['es6'], //es6 folder is the main dev folder with es6 modules and libraries in node_modules
};

export default {
  entry: './es6/entry.js',
  plugins: [
    includePaths(includePathOptions),
    nodeResolve({
      jsnext: true,
      main: true,
      browser: true
    }),
    commonjs({
      include: './es6/node_modules/**'
    }),
    babel()
  ],
  format: 'amd',
  dest: 'build/bundle.js',
  sourceMap: true
};

```

Thanks

**Comment by jamuhl** [comment]
hm...rather strange...can't say to much about it.

but stay tuned...working on building with rollup right now

so you can import from /dist/es or better said use the js:next entry

**Comment by fengshuo** [comment]
Thanks for your quick response, can't wait to see the rollup version :)

**Comment by jamuhl** [comment]
all modules now have a `jsnext:main` in package.json leading to modules being babel transpiled and keeping module pattern. so they should be 'tree-shackable' by rollup

so there is now:
main -> commonjs build
jsnext:main -> es2015 build with modules

and for umd users /i18next(.min).js generated by rollup

**Comment by jamuhl** [comment]
not sure doing the same here for i18next, i18next-xhr-backend, i18next-browser-languageDetector https://github.com/i18next/i18nextify/blob/master/rollup.config.js

only difference as i see is:
- i still got old rollup-plugin-npm
- i got no rollup-plugin-includepaths

but seems to work there...

**Comment by fengshuo** [comment]
It seems to be a plugin issue, probably the rollup-plugin-includepaths? What's odd is, I tried to uninstall and reinstall npm packages with some minor changes in rollup.config.js(and more include paths in includepathOptions, I don't think this would affect npm packages though), the error in browser this time is '18next-xhr-backend doesn't export default...', so I change the relative path again then it works....

I'll try your rollup.config.js later and see if it works.

**Comment by jamuhl** [comment]
build chains this days didn't get easier...sometimes i wished i never changed to use babel and co.

**Comment by jamuhl** [comment]
closing for now...feel free to reopen.
