### ISSUE TITLE
Issue using i18next xhr backend with RequireJS

### ISSUE THREAD

**Issue by plrenaudin** [i18next/i18next-xhr-backend#95]
Hi,
I upgraded this package from 0.3.0 to 0.5.3 and now the xhr module is not loading
```
define(['jquery','i18next', 'i18next-xhr'], function($, i18next, i18nextXHRBackend) {
  i18next.use(i18nextXHRBackend).init({ ... });
});
```
i18nextXHRBackend is undefined, I tried with the dist/umd version as well, it's not working.

What am I missing?

**Comment by jbarreiros** [comment]
I had the same problem. When defining the path, it only worked if I used "i18nextXHRBackend".

```
require.config({
  paths: {
    'i18nextXHRBackend': '../../bower_components/i18next-xhr-backend/i18nextXHRBackend',
  }
});

define(
  ['i18next', 'i18nextXHRBackend'],
  function(i18n, i18nXhr) {
    ...
  }
);
```

**Comment by plrenaudin** [comment]
Thanks a million @jbarreiros , it worked perfectly!
